version: '3.8'
services:
  odm-executor-gitlab-app:
    image: odm-platform-executor-gitlab
    container_name: odm-executor-gitlab-app
    ports:
      - "9004:9004"
    environment:
      - PARAMS_SERVICE_ADDRESS=http://localhost:8004
      - PARAMS_SERVICE_CLIENT_UUID=paramclient123
      - DATABASE_URL=jdbc:postgresql://db:5432/odmpdb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - FLYWAY_SCRIPTS_DIR=postgresql
    networks:
      - odm-net
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - odm-net
volumes:
  db:
    driver: local

networks:
  odm-net:
    driver: bridge