################
# Server Config
################
server:
  port: ${SPRING_PORT:9004}
  error:
    include-message: always
  servlet:
    context-path: /api/v1/up/executor

odm:
  productplane:
    devops-service:

    params-service:
      address: ${PARAMS_SERVICE_ADDRESS}
      client-uuid: ${PARAMS_SERVICE_CLIENT_UUID}
      client-prefix: DEVOPS_GITLAB_

################
# Pipeline Polling Config
################
polling:
  retries: 3
  interval: 10 # Time in seconds

################
# Spring Config
################
spring:
  profile: docker

  jpa:
    hibernate:
      #ddl-auto: validate
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        default_schema: ODMEXECUTOR
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console

  # Flyway https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    enabled: true
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    locations: classpath:db/migration/${FLYWAY_SCRIPTS_DIR}
    clean-on-validation-error: true

################
# Enable logging leven (log each HTTP parameter)
################
#logging:
#  level:
#    org:
#      apache:
#        http: DEBUG