CREATE TABLE IF NOT EXISTS PIPELINE_RUNS (
    PIPELINE_RUN_ID BIGINT PRIMARY KEY,
    TASK_ID BIGINT UNIQUE,
    RUN_ID VARCHAR(255),
    PROJECT VARCHAR(255),
    STATUS VARCHAR(255),
    VARIABLES TEXT,
    CREATED_AT VARCHAR(255),
    FINISHED_AT VARCHAR(255),
    GITLAB_INSTANCE_URL VARCHAR(255)
);